version: '3.7'

services:
  onthefly_integrations:
    container_name: onthefly_integrations
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './:/usr/src/app'
      - '/usr/src/app/node_modules'
    environment:
      - NODE_ENV=development
    ports:
        - '3000:3000'
